In [1]:
import numpy as np
import pandas as pd

cus_df=pd.read_csv('customers.csv')
sales_df=pd.read_csv('sales.csv')

cus_df.head()

   order_id  customer_rating
0         1                1
1         2                1
2         3                2
3         4                1
4         5                4

In [2]:
sales_df.head()

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72

In [3]:
sales_df.shape

(500, 10)

In [4]:
sales_df.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='object')